### PR TITLE
[notes] Add option to update authors file content

### PR DESCRIPTION
**Pull request by vchrombie**
This PR adds the option '--authors' which allows updating the authors file with the contributors' names.

The tests are added and the documentation is updated accordingly.

### CODE REVIEW

**Comment by vchrombie** [comment]
Thanks for the review @sduenas.

> The idea is good but it needs some modifications. It doesn't make sense that `ReleaseNotesComposer` returns the name of the authors in that way. It's doing an extra work unrelated with its main purpose which is to generate the release notes.

It completely makes sense to me.

> I would see better if, for example, you create a new class that generates the Authors file. That class can encapsulate the functions you created to update the Authors file and its content. I wouldn't write the file there though. I'd create a function that generates the full content of the file. Later, the file will be written outside of that class.

Okay, I will work on this and update the PR.

**Comment by vchrombie** [comment]
@sduenas, I have updated the PR.
It would be great if you can look at it when you have time.

**Review by sduenas — CHANGES_REQUESTED** [review]
The patch looks great but you need to add a test that covers the case when the author file doesn't exist.

**Comment by sduenas** [comment]
> The patch looks great but you need to add a test that covers the case when the author file doesn't exist.

Forget about this. I've just seen that the test was in a different file.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
